export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      position: 'relative' as const,
      width: '100%',
      background: 'transparent',
      border: 'none',
      boxShadow: 'none',
      borderRadius: '0',
      padding: '0 6px',
      overflow: 'visible',
    },
    glow: {
      position: 'absolute' as const,
      inset: 0,
      display: 'none',
      pointerEvents: 'none' as const,
    },
    listeningWaveContainer: {
      position: 'relative' as const,
      zIndex: 2,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: '100%',
      minHeight: '38px',
      mb: 2,
      pl: 1,
      pointerEvents: 'none' as const,
    },
    listeningWavePill: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 3,
      px: 3,
      py: 2,
      borderRadius: '999px',
      background: 'rgba(15, 23, 42, 0.78)',
      border: '1px solid rgba(125, 211, 252, 0.26)',
      boxShadow: '0 14px 34px rgba(8, 47, 73, 0.24)',
      backdropFilter: 'blur(12px)',
    },
    listeningWaveDot: {
      width: '9px',
      height: '9px',
      borderRadius: '999px',
      background: '#22d3ee',
      boxShadow: '0 0 0 4px rgba(34, 211, 238, 0.14), 0 0 18px rgba(34, 211, 238, 0.7)',
      flexShrink: 0,
    },
    listeningWaveBars: {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
      height: '22px',
    },
    listeningWaveBar: {
      width: '4px',
      height: '16px',
      borderRadius: '999px',
      background: 'linear-gradient(180deg, #a7f3d0 0%, #22d3ee 55%, #38bdf8 100%)',
      boxShadow: '0 0 12px rgba(56, 189, 248, 0.42)',
      transformOrigin: 'center',
    },
    listeningWaveText: {
      color: 'whiteAlpha.950',
      fontSize: '13px',
      fontWeight: 700,
      lineHeight: 1,
      whiteSpace: 'nowrap' as const,
    },
    scrollArea: {
      position: 'relative' as const,
      display: 'flex',
      flexDirection: 'column' as const,
      gap: 4,
      maxHeight: '172px',
      overflowY: 'auto' as const,
      pr: 1,
      pl: 1,
      css: {
        '&::-webkit-scrollbar': {
          width: '6px',
        },
        '&::-webkit-scrollbar-thumb': {
          background: 'rgba(226, 232, 240, 0.18)',
          borderRadius: '999px',
        },
      },
    },
    row: {
      display: 'flex',
      width: '100%',
    },
    meta: {
      fontSize: '11px',
      fontWeight: 700,
      letterSpacing: '0.08em',
      textTransform: 'uppercase' as const,
      mb: 1,
      opacity: 0.78,
    },
    bubble: {
      display: 'inline-block',
      width: 'max-content',
      maxWidth: '92%',
      borderRadius: '18px',
      px: 4,
      py: 3,
      border: '1px solid transparent',
      boxShadow: '0 12px 32px rgba(15, 23, 42, 0.24)',
    },
    humanBubble: {
      background: 'linear-gradient(135deg, rgba(30, 41, 59, 0.94) 0%, rgba(51, 65, 85, 0.88) 100%)',
      borderColor: 'rgba(148, 163, 184, 0.18)',
      color: 'white',
      borderBottomRightRadius: '8px',
    },
    aiBubble: {
      background: 'linear-gradient(135deg, rgba(180, 83, 9, 0.92) 0%, rgba(120, 53, 15, 0.88) 100%)',
      borderColor: 'rgba(251, 191, 36, 0.18)',
      color: 'white',
      borderBottomLeftRadius: '8px',
    },
    bubbleText: {
      fontSize: '18px',
      lineHeight: '1.65',
      whiteSpace: 'normal' as const,
      wordBreak: 'normal' as const,
      overflowWrap: 'break-word' as const,
    },
    systemContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      minHeight: '60px',
    },
    systemPill: {
      px: 5,
      py: 3,
      borderRadius: '999px',
      border: '1px solid rgba(148, 163, 184, 0.18)',
      background: 'rgba(15, 23, 42, 0.72)',
      boxShadow: '0 18px 48px rgba(15, 23, 42, 0.22)',
    },
    systemText: {
      color: 'whiteAlpha.900',
      fontSize: '17px',
      fontWeight: 600,
      textAlign: 'center' as const,
      lineHeight: '1.5',
    },
  },
  wsStatus: {
    container: {
      position: 'relative',
      zIndex: 2,
      padding: '8px 14px',
      borderRadius: '999px',
      fontSize: '14px',
      fontWeight: 'medium',
      color: 'white',
      background: 'rgba(15, 23, 42, 0.64)',
      border: '1px solid rgba(255,255,255,0.12)',
      backdropFilter: 'blur(10px)',
      boxShadow: '0 10px 24px rgba(15, 23, 42, 0.18)',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      _hover: {
        opacity: 0.8,
      },
    },
    dot: {
      width: '10px',
      height: '10px',
      borderRadius: 'full',
      boxShadow: '0 0 0 2px rgba(255,255,255,0.12)',
      flexShrink: 0,
    },
    text: {
      color: 'whiteAlpha.950',
      fontSize: '14px',
      fontWeight: 600,
      lineHeight: 1,
    },
  },
};
