export const STAGE_SAFE_AREA_MAX_WIDTH = 860;
export const STAGE_SAFE_AREA_MAX_HEIGHT = 920;
export const STAGE_SAFE_AREA_SIDE_PADDING = 40;
export const STAGE_SAFE_AREA_TOP_BOTTOM_PADDING = 72;

export const STAGE_SAFE_AREA_WIDTH = `min(calc(100% - ${STAGE_SAFE_AREA_SIDE_PADDING}px), ${STAGE_SAFE_AREA_MAX_WIDTH}px)`;
export const STAGE_SAFE_AREA_HEIGHT = `min(calc(100% - ${STAGE_SAFE_AREA_TOP_BOTTOM_PADDING}px), ${STAGE_SAFE_AREA_MAX_HEIGHT}px)`;
export const STAGE_DIALOG_WIDTH = "min(calc(100% - 48px), 720px)";
export const STAGE_FOOTER_HEIGHT = "196px";
export const STAGE_SUBTITLE_COLLAPSED_BOTTOM = "68px";
export const STAGE_SUBTITLE_EXPANDED_BOTTOM = "128px";
